name: Deploy Agentiss via FTP na Hostinger

on:
  push:
    branches:
      - main
      - work

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Build do projeto
        run: npm run build

      - name: Mostrar arquivos gerados
        run: ls -al dist/

      - name: Deploy FTP para Hostinger (sem apagar nada)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          port: 21
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}

          # pasta local com o build
          local-dir: dist/

          # caminho do domínio principal no painel Hostinger
          server-dir: /domains/agentiss.shop/public_html/

          # NÃO limpar o servidor antes do upload
          dangerous-clean-slate: false

          # logs úteis para depurar
          log-level: verbose
          dry-run: false

          # preservar/ignorar estes itens no servidor (não apaga e não substitui)
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/*.map
            .htaccess
            robots.txt
            sitemap.xml
            .well-known/**
            backups/**
            storage/**
            uploads/**
            analytics/**
            _private/**
